/* Generated By:JJTree: Do not edit this line. ASTADD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTADD extends SimpleNode {
  public ASTADD(int id) {
    super(id);
  }

  public ASTADD(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	  return "+";
  }

}
/* JavaCC - OriginalChecksum=a27409a1dcc9e09ff4c35def8683db96 (do not edit this line) */
