/* Generated By:JJTree: Do not edit this line. ASTArrayAcc.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAcc extends SimpleNode {
  public ASTArrayAcc(int id) {
    super(id);
  }

  public ASTArrayAcc(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e60e5c4b261a9ff761baa088828aacf1 (do not edit this line) */
