/* Generated By:JJTree: Do not edit this line. ASTAND.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAND extends SimpleNode {
  public ASTAND(int id) {
    super(id);
  }

  public ASTAND(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	return "&&";
  }

}
/* JavaCC - OriginalChecksum=4a4a14b55f8b490d21ea3ced19324c5c (do not edit this line) */
