/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {

  String class_name = "";
  String extends_class = "";

  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "class: " + class_name + (extends_class.equals("") ? "" : ("extends" + extends_class));
  }

}
/* JavaCC - OriginalChecksum=accd6c615f837a4f4156eee86c99e791 (do not edit this line) */
