/* Generated By:JJTree: Do not edit this line. ASTDIV.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDIV extends SimpleNode {
  public ASTDIV(int id) {
    super(id);
  }

  public ASTDIV(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	return "/";
  }

}
/* JavaCC - OriginalChecksum=7c3f486853a5965468791335eb31af69 (do not edit this line) */
