/* Generated By:JJTree: Do not edit this line. ASTDIV.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDIV extends SimpleNode {
  public ASTDIV(int id) {
    super(id);
  }

  public ASTDIV(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	return "/";
  }

  public String semanticAnalysis(SymbolTable table, String functionName) throws Exception {
	String type;

	if (children != null) {
		for (int i = 0; i < children.length; ++i) {
			SimpleNode n = (SimpleNode) children[i];
			if (n != null) {
				type = n.semanticAnalysis(table,functionName);

				if(!type.equals("int"))
					throw new Exception("/ expected integer but found " + type);
			}
		}
	}

	return "int";
  }

  public void generateCode(StringBuilder builder, SymbolTable ST, String functionName) {
	((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
	((SimpleNode)children[1]).generateFunctionCode(builder, ST, functionName);
	builder.append("idiv\n");
  }

  public void generateFunctionCode(StringBuilder builder, SymbolTable ST, String functionName) {
	  generateCode(builder,ST,functionName);
  }

}
/* JavaCC - OriginalChecksum=7c3f486853a5965468791335eb31af69 (do not edit this line) */
