/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(jmm p, int id) {
    super(p, id);
  }

  public String toString(){
	  return "";
  }

}
/* JavaCC - OriginalChecksum=79fcb1931dc002d267ff8fc7e60208c9 (do not edit this line) */
