/* Generated By:JJTree: Do not edit this line. ASTLESS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLESS extends SimpleNode {
  public ASTLESS(int id) {
    super(id);
  }

  public ASTLESS(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	return "<";
  }


}
/* JavaCC - OriginalChecksum=80e981cb70049e1d63295d41a7f844d5 (do not edit this line) */
