/* Generated By:JJTree: Do not edit this line. ASTLESS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLESS extends SimpleNode {
  public ASTLESS(int id) {
    super(id);
  }

  public ASTLESS(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	return "<";
  }

  public String semanticAnalysis(SymbolTable table, String functionName) throws Exception {
	String type;

	if (children != null) {
		for (int i = 0; i < children.length; ++i) {
			SimpleNode n = (SimpleNode) children[i];
			if (n != null) {
				type = n.semanticAnalysis(table,functionName);

				if(!type.equals("int"))
					throw new Exception("< expected integer but found " + type);
			}
		}
	}

	return "boolean";
  }
}
/* JavaCC - OriginalChecksum=80e981cb70049e1d63295d41a7f844d5 (do not edit this line) */
