/* Generated By:JJTree: Do not edit this line. ASTLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLiteral extends SimpleNode {
	String identifier = "";

  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(jmm p, int id) {
    super(p, id);
  }

  public String toString(){
	return "Expression: " + identifier;
  }
}
/* JavaCC - OriginalChecksum=a8d48e9a57e0088d4ff5320e922f78d0 (do not edit this line) */
