/* Generated By:JJTree: Do not edit this line. ASTLT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLT extends SimpleNode {
  public ASTLT(int id) {
    super(id);
  }

  public ASTLT(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c236a23c0b0d3d792bf55da32fbbd6f5 (do not edit this line) */
