/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainDeclaration extends SimpleNode {
	String args = "";

  public ASTMainDeclaration(int id) {
    super(id);
  }

  public ASTMainDeclaration(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "main: param: " + this.args;
  }

}
/* JavaCC - OriginalChecksum=0c5227e4bd79d47833b58d1707cedc06 (do not edit this line) */
