/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.Hashtable;

public
class ASTMainDeclaration extends SimpleNode {
	String args = "";

  public ASTMainDeclaration(int id) {
    super(id);
  }

  public ASTMainDeclaration(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "main: param: " + this.args;
  }

  public void buildST(SymbolTable table, String functionName) throws Exception {
	if(table.functions.get("main") != null)
		throw new Exception("Function main declared twice");

	FunctionSymbol functionSymbol = new FunctionSymbol("void");
	table.functions.put("main", functionSymbol);

	Symbol mainSymbol = new Symbol("String[]", args);
	functionSymbol.params.put(args,mainSymbol);
	
	if (children != null) {
		for (int i = 0; i < children.length; ++i) {
			SimpleNode n = (SimpleNode) children[i];
			if (n != null) {
				n.buildST(table, "main");
			}
		}
	}
}

}
/* JavaCC - OriginalChecksum=0c5227e4bd79d47833b58d1707cedc06 (do not edit this line) */
