/* Generated By:JJTree: Do not edit this line. ASTOtherLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOtherLiteral extends SimpleNode {
	String type = "";
	String identifier = "";

  public ASTOtherLiteral(int id) {
    super(id);
  }

  public ASTOtherLiteral(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	switch(type)
	{
		case "[]": return "[...]";
		case "length": return "length";
		case "call": return "call: " + identifier;
	}

	return "";
  }

}
/* JavaCC - OriginalChecksum=6a67081bb7fb5f77aa5f878ca7d3dcab (do not edit this line) */
