/* Generated By:JJTree: Do not edit this line. ASTParameters.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameters extends SimpleNode {
  public ASTParameters(int id) {
    super(id);
  }

  public ASTParameters(jmm p, int id) {
    super(p, id);
  }

  public String[] getParameters() {
	  String[] res = new String[children.length];

	  for(int i = 0; i < children.length; i++) {
		  ASTParameter parameter = (ASTParameter) children[i];
		  ASTType type = (ASTType) parameter.children[0];
		  res[i] = type.name;

		  if(type.isArray)
		  	res[i] += "[]";
	  }

	  return res;
  }
}
/* JavaCC - OriginalChecksum=b49c5ca506c6a4e5c4eaaaeb3fecef9c (do not edit this line) */
