/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProgram extends SimpleNode {
  public ASTProgram(int id) {
    super(id);
  }

  public ASTProgram(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=756f4a495f19adc514394003f67bd446 (do not edit this line) */
