/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReturn extends SimpleNode {
  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	  return "return";
  }

}
/* JavaCC - OriginalChecksum=726225cb80eeed4c80172f99f8e094ff (do not edit this line) */
