/* Generated By:JJTree: Do not edit this line. ASTStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement extends SimpleNode {
	String type = "";
	String identifier = "";
	static int labels = 0;

  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    switch(type){
		case "multiple": return "Multiple Statements";
		case "if": return "if...else";
		case "while": return "while";
		case "[]=": return identifier + "[...]=";
		case "=": return identifier + " =";
	}

	return "Statement";
  }

	public void generateCode(StringBuilder builder, SymbolTable ST, String functionName) {
		if(type.equals("multiple")) {
			super.generateCode(builder,ST,functionName);
		}
		if(type.equals("if")) {
			int label = labels;
			labels++;
			((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
			builder.append("ifeq ELSE" + label + "\n");
			((SimpleNode)children[1]).generateCode(builder, ST, functionName);
			builder.append("goto ENDIF" + label + "\nELSE" + label + ":\n");
			((SimpleNode)children[2]).generateCode(builder, ST, functionName);
			builder.append("ENDIF" + label + ":\n");
			return;
		}

		if(type.equals("while")) {
			int label = labels;
			labels++;
			builder.append("WHILE" + label + ":\n");
			((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
			builder.append("ifeq ENDWHILE" + label + "\n");
			((SimpleNode)children[1]).generateCode(builder, ST, functionName);
			builder.append("goto WHILE" + label + "\nENDWHILE" + label + ":\n");

			return;
		}

		if(type.equals("=")) {
			if(identifier.equals("this")) {
				((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
				builder.append("astore_0");
			} else {
				Symbol symbol;
				if ((symbol = ST.functions.get(functionName).locals.get(identifier)) != null) {
					((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
					builder.append("istore_" + symbol.order);
				}
				else if ((symbol = ST.functions.get(functionName).params.get(identifier)) != null) {
					((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
					builder.append("istore_" + symbol.order);
				}
				else if((symbol = ST.symbols.get(identifier)) != null) {
					builder.append("aload_0\n");

					((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);

					if(symbol.type.equals("boolean"))
						builder.append("putfield " + ST.className + "/" + identifier + "Z" );
	
					else if(symbol.type.equals("int"))
						builder.append("putfield " + ST.className + "/" + identifier + "I" );

					else if(symbol.type.equals("int[]"))
						builder.append("putfield " + ST.className + "/" + identifier + "[I" );
	
					else builder.append("putfield " + ST.className + "/" + identifier + "L" );

					builder.append("\n");
				} 
			}
		}

		if(type.equals("[]=")) {
			Symbol symbol;
			if ((symbol = ST.functions.get(functionName).locals.get(identifier)) != null) {
				((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
				builder.append("astore_" + symbol.order);
			}
			else if ((symbol = ST.functions.get(functionName).params.get(identifier)) != null) {
				((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
				builder.append("astore_" + symbol.order);
			}
			else if((symbol = ST.symbols.get(identifier)) != null) {
				builder.append("aload_0\n");

				if(symbol.type.equals("boolean"))
					builder.append("getfield " + ST.className + "/" + identifier + "Z" );

				else if(symbol.type.equals("int"))
					builder.append("getfield " + ST.className + "/" + identifier + "I" );

				else if(symbol.type.equals("int[]"))
					builder.append("getfield " + ST.className + "/" + identifier + "[I" );

				else builder.append("getfield " + ST.className + "/" + identifier + "L" );

				builder.append("\n");
			}
			
			((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
			((SimpleNode)children[1]).generateFunctionCode(builder, ST, functionName);

			builder.append("iastore\n");
		}

		super.generateFunctionCode(builder,ST,functionName);
	}

}
/* JavaCC - OriginalChecksum=2405f96baf2205473865575b3fc06196 (do not edit this line) */
