/* Generated By:JJTree: Do not edit this line. ASTStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement extends SimpleNode {
	String type = "";
	String identifier = "";

  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    switch(type){
		case "multiple": return "Multiple Statements";
		case "if": return "if...else";
		case "while": return "while";
		case "[]=": return identifier + "[...]=";
		case "=": return identifier + "=";
	}

	return "Statement";
  }

}
/* JavaCC - OriginalChecksum=2405f96baf2205473865575b3fc06196 (do not edit this line) */
