/* Generated By:JavaCC: Do not edit this line. jmmTreeConstants.java Version 6.0_1 */
public interface jmmTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTPROGRAM = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMAINDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTPARAMETERS = 6;
  public int JJTPARAMETER = 7;
  public int JJTTYPE = 8;
  public int JJTSTATEMENT = 9;
  public int JJTVOID = 10;
  public int JJTAND = 11;
  public int JJTLESS = 12;
  public int JJTADD = 13;
  public int JJTSUB = 14;
  public int JJTMULT = 15;
  public int JJTDIV = 16;
  public int JJTLITERAL = 17;
  public int JJTOTHERLITERAL = 18;
  public int JJTMETHODPARAMS = 19;


  public String[] jjtNodeName = {
    "error_skipto",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Parameters",
    "Parameter",
    "Type",
    "Statement",
    "void",
    "AND",
    "LESS",
    "ADD",
    "SUB",
    "MULT",
    "DIV",
    "Literal",
    "OtherLiteral",
    "MethodParams",
  };
}
/* JavaCC - OriginalChecksum=084fd53cf084f6be03f49f5666a5a9c6 (do not edit this line) */
