/* Generated By:JavaCC: Do not edit this line. jmmTreeConstants.java Version 6.0_1 */
package jmm;

public interface jmmTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTPROGRAM = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMAINDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTPARAMETERS = 6;
  public int JJTPARAMETER = 7;
  public int JJTRETURN = 8;
  public int JJTTYPE = 9;
  public int JJTSTATEMENT = 10;
  public int JJTVOID = 11;
  public int JJTAND = 12;
  public int JJTLESS = 13;
  public int JJTADD = 14;
  public int JJTSUB = 15;
  public int JJTMULT = 16;
  public int JJTDIV = 17;
  public int JJTLITERAL = 18;
  public int JJTOTHERLITERAL = 19;
  public int JJTMETHODPARAMS = 20;


  public String[] jjtNodeName = {
    "error_skipto",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Parameters",
    "Parameter",
    "Return",
    "Type",
    "Statement",
    "void",
    "AND",
    "LESS",
    "ADD",
    "SUB",
    "MULT",
    "DIV",
    "Literal",
    "OtherLiteral",
    "MethodParams",
  };
}
/* JavaCC - OriginalChecksum=8a01b2d2d82a84cf7274f3f8175d1e2f (do not edit this line) */
