/* Generated By:JJTree: Do not edit this line. ASTAND.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import jmm.*;

public
class ASTAND extends SimpleNode {
	static int labels = 0;
  public ASTAND(int id) {
    super(id);
  }

  public ASTAND(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	return "&&";
  }

  public String semanticAnalysis(SymbolTable table, String functionName) throws Exception {
	String type;

	if (children != null) {
		for (int i = 0; i < children.length; ++i) {
			SimpleNode n = (SimpleNode) children[i];
			if (n != null) {
				type = n.semanticAnalysis(table,functionName);

				if(!type.equals("boolean") && !type.equals(""))
					throw new Exception("&& expected boolean but found " + type);
			}
		}
	}

	return "boolean";
  }

  public void generateCode(StringBuilder builder, SymbolTable ST, String functionName) {
	  int label = labels;
	  labels += 2;
	  
	((SimpleNode)children[0]).generateFunctionCode(builder, ST, functionName);
	builder.append("ifeq AND" + label + "\n");
	((SimpleNode)children[1]).generateFunctionCode(builder, ST, functionName);
	builder.append("ifeq AND" + label + "\n");
	
	builder.append("iconst_1\ngoto AND" + ((int) label + 1) + "\nAND" + label + ":\niconst_0\nAND" + ((int) label + 1) + ":\n");
  }

  public void generateFunctionCode(StringBuilder builder, SymbolTable ST, String functionName) {
	generateCode(builder,ST,functionName);
  }

}
/* JavaCC - OriginalChecksum=4a4a14b55f8b490d21ea3ced19324c5c (do not edit this line) */
