/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import jmm.*;

public class ASTMethodDeclaration extends SimpleNode {
	public String name = "";

	public ASTMethodDeclaration(int id) {
		super(id);
	}

	public ASTMethodDeclaration(jmm p, int id) {
		super(p, id);
	}

	public String toString() {
		return "method: " + this.name;
	}

	public void buildST(SymbolTable table, String functionName) throws Exception {
		if(table.functions.get(name) != null)
			throw new Exception("Function" + name + "declared twice");

		ASTType type = (ASTType) children[0];
		String typeName = type.name;
		if(type.isArray) typeName += "[]";
		
		FunctionSymbol functionSymbol = new FunctionSymbol(typeName);
		table.functions.put(name, functionSymbol);
		
		if (children != null) {
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					try{
						n.buildST(table, name);
					}
					catch(Exception e){
						System.out.println(e.getMessage());
					}
				}
			}
		}
	}

	public String semanticAnalysis(SymbolTable table, String functionName) throws Exception {
		if (children != null) {
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					try{
						n.semanticAnalysis(table, name);
					  }  
					  catch(Exception e){
						System.out.println(e.getMessage());
					  }
				}
			}
		}
	
		return "";
	}

	public void generateCode(StringBuilder builder, SymbolTable ST, String functionName) {
		builder.append(".method public " + name + "(");

		if(children.length >= 2 && children[1] instanceof ASTParameters) {
			String[] parameters = ((ASTParameters)children[1]).getParameters();

			for(int i = 0; i < parameters.length; i++){
				if(parameters[i].equals("boolean"))
					builder.append("Z");

				else if(parameters[i].equals("int"))
					builder.append("I");

				else if(parameters[i].equals("int[]"))
					builder.append("[I");

				else if(parameters[i].equals(ST.className))
				builder.append("L" + ST.className + "");

				else builder.append("Ljava/lang/" + parameters[i] + ";");
			}
		}

		builder.append(")");

		String returnType = ((ASTType) children[0]).name;

		if(((ASTType) children[0]).isArray)
			returnType += "[]";
		
		if(returnType.equals("boolean"))
			builder.append("Z");

		else if(returnType.equals("int"))
			builder.append("I" );

		else if(returnType.equals("int[]"))
			builder.append("[I" );

        else if(returnType.equals(ST.className))
          builder.append("L" + ST.className);

		else builder.append("Ljava/lang/" + returnType + ";");

		builder.append("\n.limit stack " + ((int) depth() * 2) + "\n.limit locals " + ((int) ST.functions.get(name).params.size() + ST.functions.get(name).locals.size() + 1  - ST.functions.get(name).unusedLocals) + "\n");
		
		if (children != null) {
			for (int i = 0; i < children.length - 1; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					n.generateCode(builder,ST,name);
				}
			}
			SimpleNode n = (SimpleNode) children[children.length - 1];
			n.generateFunctionCode(builder,ST,name);
		}

		if(returnType.equals("boolean") || returnType.equals("int"))
			builder.append("ireturn\n.end method\n\n");

		else builder.append("areturn\n.end method\n\n");
	}

	public void optimizeO(SymbolTable ST, String functionName) {
		if (children != null) {
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					n.optimizeO(ST,name);
				}
			}
		}
	}
}
/*
 * JavaCC - OriginalChecksum=11d41e8ab96800088d3eba562689294a (do not edit this
 * line)
 */
