/* Generated By:JJTree: Do not edit this line. ASTType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import jmm.*;

public
class ASTType extends SimpleNode {
	public String name = "";
	public boolean isArray = false;

  public ASTType(int id) {
    super(id);
  }

  public ASTType(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
	  return "type: " + name + (isArray ? "[]" : "");
  }

}
/* JavaCC - OriginalChecksum=e2569642d3436ea4af5663b3e42891a2 (do not edit this line) */
